import { NextResponse } from "next/server";
import { readDb,writeDb,uid,getUser,consumeFeature } from "@/lib/db";
import { blockedUserIdsFor, isBlockedBetween } from "@/lib/safety";
import { relationalCommunicationEnabled, listRelationalMessages, createRelationalMessage, markRelationalMessagesRead } from "@/lib/relational-communication";
const now=()=>new Date().toISOString();
export async function GET(request){ const user=await getUser(request); if(!user)return NextResponse.json({error:"Unauthorized"},{status:401}); if(relationalCommunicationEnabled())return NextResponse.json(await listRelationalMessages(user.id)); const db=await readDb(); const blockedIds=blockedUserIdsFor(db,user.id); const messages=db.messages.filter(m=>(m.fromUserId===user.id||m.toUserId===user.id)&&!blockedIds.has(m.fromUserId===user.id?m.toUserId:m.fromUserId)).sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt)); const enriched=messages.map(m=>{const otherId=m.fromUserId===user.id?m.toUserId:m.fromUserId;const profile=db.profiles.find(p=>p.userId===otherId);return {...m,otherProfile:profile?{id:profile.id,name:profile.name,initials:profile.initials,verified:profile.verified,primaryPhotoData:profile.primaryPhotoData}:null}}); return NextResponse.json({messages:enriched,unread:messages.filter(m=>m.toUserId===user.id&&!m.read).length}); }
export async function POST(request){ const user=await getUser(request); if(!user)return NextResponse.json({error:"Unauthorized"},{status:401}); const {profileId,text}=await request.json(); const clean=String(text||"").trim(); if(!clean)return NextResponse.json({error:"Message cannot be empty."},{status:400}); if(clean.length>1000)return NextResponse.json({error:"Message is too long."},{status:400});
 if(relationalCommunicationEnabled()){ const db=await readDb(); const quota=consumeFeature(db,user.id,"messages"); if(!quota.allowed)return NextResponse.json({error:`Your ${quota.plan?.name||"Free"} plan message limit has been reached. Upgrade to continue.`},{status:403}); const result=await createRelationalMessage(user.id,String(profileId||""),clean); if(result.error)return NextResponse.json({error:result.error},{status:result.status}); db.notifications=db.notifications||[];db.notifications.unshift({id:uid("n"),userId:result.targetUserId,type:"message_received",title:"New message",body:`${user.firstName} ${user.lastName} sent you a message.`,profileId:db.profiles.find(p=>p.userId===user.id)?.id||null,read:false,createdAt:now()}); await writeDb(db); return NextResponse.json({message:result.message},{status:201}); }
 const db=await readDb(); const profile=db.profiles.find(p=>p.id===profileId); if(!profile)return NextResponse.json({error:"Recipient not found."},{status:404}); if(profile.userId===user.id)return NextResponse.json({error:"You cannot message yourself."},{status:400}); if(isBlockedBetween(db,user.id,profile.userId))return NextResponse.json({error:"Messaging is unavailable because one of these members has blocked the other."},{status:403}); const accepted=db.interests.some(i=>i.status==="Accepted"&&((i.fromUserId===user.id&&i.toUserId===profile.userId)||(i.fromUserId===profile.userId&&i.toUserId===user.id))); if(!accepted)return NextResponse.json({error:"Messaging becomes available after an interest is accepted."},{status:403}); const quota=consumeFeature(db,user.id,"messages"); if(!quota.allowed)return NextResponse.json({error:`Your ${quota.plan?.name||"Free"} plan message limit has been reached. Upgrade to continue.`},{status:403}); const createdAt=now(); const message={id:uid("m"),fromUserId:user.id,toUserId:profile.userId,profileId,text:clean,read:false,createdAt,updatedAt:createdAt}; db.messages.push(message); await writeDb(db); return NextResponse.json({message},{status:201}); }
export async function PATCH(request){ const user=await getUser(request); if(!user)return NextResponse.json({error:"Unauthorized"},{status:401}); const {otherUserId}=await request.json(); if(relationalCommunicationEnabled())return NextResponse.json({changed:await markRelationalMessagesRead(user.id,otherUserId?String(otherUserId):null)}); const db=await readDb(); let changed=0; db.messages=db.messages.map(m=>{if(m.toUserId===user.id&&(!otherUserId||m.fromUserId===otherUserId)&&!m.read){changed++;return {...m,read:true,readAt:now(),updatedAt:now()}}return m}); await writeDb(db); return NextResponse.json({changed}); }
